lib/res_web/router.ex
defmodule ResWeb.Router do
  use ResWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ResWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PlantController, :form
    post "/list", PlantController, :show
    get "/list", PlantController, :show
    resources "/list", PlantController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ResWeb do
  #   pipe_through :api
  # end
end

lib/res/application.ex
defmodule Res.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Res.Repo, []),
      # Start the endpoint when the application starts
      supervisor(ResWeb.Endpoint, []),
      # Start your own worker by calling: Res.Worker.start_link(arg1, arg2, arg3)
      # worker(Res.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Res.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ResWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/res/data_access.ex
defmodule Res.DataAccess do
  @moduledoc """
  The Accounts context.
  """

  alias Res.Repo

  # alias Vueshatter.Models.LoanHistory
  alias  Res.Model.Plant

  def create_plant(attrs \\ %{}) do
    %Plant{}
    |> Plant.changeset(attrs)
    |> Repo.insert()
  end
end

lib/res/repo.ex
defmodule Res.Repo do
  use Ecto.Repo, otp_app: :res

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/res_web/controllers/page_controller.ex
defmodule ResWeb.PageController do
  use ResWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/res_web/controllers/plant_controller.ex
defmodule ResWeb.PlantController do
  use ResWeb, :controller
  alias Res.DataAccess
  alias Res.Repo
  import Ecto.Query, only: [from: 2]
  alias Res.Model.Plant

  def form(conn, _params) do
    render conn, "form.html"
  end
  def show(conn, _params) do
    plant_list = Repo.all(Plant)
    render(conn, "show.html", plant_list: plant_list)
  end
end

lib/res_web/views/error_view.ex
defmodule ResWeb.ErrorView do
  use ResWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/res_web/views/layout_view.ex
defmodule ResWeb.LayoutView do
  use ResWeb, :view
end

lib/res_web/views/page_view.ex
defmodule ResWeb.PageView do
  use ResWeb, :view
end

lib/res_web/views/plant_view.ex
defmodule ResWeb.PlantView do
  use ResWeb, :view
end

lib/res_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Res!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/res_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/res_web/templates/plant/form.html.eex
<h1>Enter rental details</h1>

<%= form_for @conn, plant_path(@conn, :show), fn res -> %>

<div id="plant">
  <form></form>
</div>
<div class="form-group col-sm-2">
  Plant name
</div>

<div class="form-group col-sm-6">
   <%= text_input res, :name, class: "form-control", id: "name" %>
</div>
<br />
<br />
<br />
<div class="form-group col-sm-2">
  Start date
  </div>
<div class="form-group col-sm-4">
   <%= text_input res, :name, class: "form-control", id: "start_date" %>
</div>
<br />
<br />
<br />
<div class="form-group col-sm-2">
  End date
  </div>
<div class="form-group col-sm-4">
   <%= text_input res, :name, class: "form-control", id: "end_date" %>
</div>

<div class="form-group col-sm-7">
    <%= submit "Query plant catalog", class: "btn btn-primary", id: "submit_button" %>
</div>
<% end %>

lib/res_web/templates/plant/show.html.eex
 <table class="table"> 
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody> 
  <%= for plant <- @plant_list do %>
  <tr>
    <td><%= plant.name  %></td>
    <td><%= plant.description  %></td>
    <td><%= plant.price %> </td>
    <td><%= link "Select", to: plant_path(@conn, :form) %></td>
   </tr>  
     
<% end %>
  </tbody>
</table>
</div>